project:
  type: website
  output-dir: docs

website:
  title: "Einar Paz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.pdf
        text: CV

    # tools:
    #   - icon: linkedin
    #     href: "https://www.linkedin.com/in/einar-paz-6a639aa2/"
    #     aria-label: LinkedIn
    #     target: _blank

    #   - icon: envelope
    #     href: "mailto:einarpaz@utexas.edu"
    #     aria-label: Email

  page-footer:
    center: "© 2026 Einar Paz"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false